name: Display Name on Push

on:
  push:
    branches:
      - main

jobs:
  display_name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Name
      run: |
        echo "First Name: Artem"
        echo "Last Name: Shestak"
